[project]
name = "movie-recommendation-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [    
    "langchain-openai>=1.1.6",
    "ollama>=0.6.1",
    "qdrant-client>=1.16.2",
    "sentence-transformers>=5.2.0",
    "streamlit>=1.52.2",    
    "torch==2.6.0",
    # legacy
    "chromadb>=1.5.1", 
    "fastembed>=0.7.4",       
]

[project.optional-dependencies]
cpu = ["torch==2.6.0"]
gpu = ["torch==2.6.0+cu126"]

# https://docs.astral.sh/uv/guides/integration/pytorch/#configuring-accelerators-with-optional-dependencies
[tool.uv]
conflicts = [
  [ { extra = "cpu" }, { extra = "gpu" }, ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu126", extra = "gpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[dependency-groups]
dev = [
     "pytest>=8.0.0",
]
